### ISSUE TITLE
New Gateway Requires Battery

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/loraham#7]
The new Gateway code goes to sleep immediately when no battery is wired to the feather board.  A partial fix would be to never sleep when the serial port is connected.

Assigning to @sharph.  Close this issue when the new gateway code works reliably on USB power without a battery.

**Comment by akadamson** [comment]
This appears to not be the case.  If you undef the RTC define, the feather will run the new gateway code on usb power only.  The problem was that the RTC define when active, disactivates the USB port on the feature making it appear to not be working.

**Comment by travisgoodspeed** [comment]
Closing in favor of #8, which better explains the issue at hand.
